flowchart LR

Prowlarr[Prowlarr Indexer] --> Radarr
Prowlarr --> Sonarr

Radarr --> Qbit[qBittorrent]
Sonarr --> Qbit

Qbit --> Downloads[Downloads (/media)]
Downloads --> Radarr
Downloads --> Sonarr
Downloads --> Jellyfin[Jellyfin Library Scanner]
---
